using System;
using System.Collections.Generic;
using MonitorImpresoras.Domain.Entities;
using MonitorImpresoras.Domain.Enums;

namespace MonitorImpresoras.Domain.DTOs
{
    /// <summary>
    /// DTO para crear una nueva alerta
    /// </summary>
    public class CreateAlertDTO
    {
        public Guid TenantId { get; set; }
        public string Description { get; set; } = string.Empty;
        public AlertType Type { get; set; }
        public AlertSeverity Severity { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
        public string? Source { get; set; }
        public string? Title { get; set; }
    }

    /// <summary>
    /// DTO para actualizar una alerta
    /// </summary>
    public class UpdateAlertDTO
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public AlertSeverity? Severity { get; set; }
        public AlertStatus? Status { get; set; }
    }

    /// <summary>
    /// DTO para información de alerta
    /// </summary>
    public class AlertDTO
    {
        public Guid Id { get; set; }
        public Guid TenantId { get; set; }
        public string Description { get; set; } = string.Empty;
        public AlertType Type { get; set; }
        public AlertSeverity Severity { get; set; }
        public AlertStatus Status { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
        public string? Source { get; set; }
        public string? Title { get; set; }
        public string? ResolutionNotes { get; set; }
    }

    /// <summary>
    /// DTO para filtrar alertas
    /// </summary>
    public class AlertFilterDTO
    {
        public Guid? TenantId { get; set; }
        public AlertType? Type { get; set; }
        public AlertSeverity? Severity { get; set; }
        public AlertStatus? Status { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public int PageNumber { get; set; } = 1;
        public int PageSize { get; set; } = 20;
    }

    /// <summary>
    /// DTO para estadísticas de alertas
    /// </summary>
    public class AlertStatsDTO
    {
        public int TotalAlerts { get; set; }
        public int OpenAlerts { get; set; }
        public int AcknowledgedAlerts { get; set; }
        public int ResolvedAlerts { get; set; }
        public int HighSeverityAlerts { get; set; }
        public int MediumSeverityAlerts { get; set; }
        public int LowSeverityAlerts { get; set; }
        public Dictionary<AlertType, int> AlertsByType { get; set; } = new();
        public Dictionary<AlertStatus, int> AlertsByStatus { get; set; } = new();
        public Dictionary<AlertSeverity, int> AlertsBySeverity { get; set; } = new();
    }
}
