namespace MonitorImpresoras.Domain.DTOs
{
    /// <summary>
    /// DTO for alert information
    /// </summary>
    public class AlertDTO
    {
        public Guid Id { get; set; }
        public Guid TenantId { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public string Severity { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? Source { get; set; }
        public string? ResolutionNotes { get; set; }
        public Guid? PrinterId { get; set; }
        public string? PrinterName { get; set; }
        public string? AcknowledgedBy { get; set; }
        public DateTime? AcknowledgedAt { get; set; }
        public string? Message { get; set; }
    }
}
