namespace MonitorImpresoras.Domain.DTOs
{
    /// <summary>
    /// DTO for creating a new alert
    /// </summary>
    public class CreateAlertDTO
    {
        public Guid TenantId { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public string Severity { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; } = false;
        public string? Source { get; set; }
        public Guid? PrinterId { get; set; }
        public string? Metadata { get; set; }
    }
}
